
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-json
  - id: pretty-format-json
    args:
      - "--autofix"
  - id: trailing-whitespace

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: cargo-check

- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.7
  hooks:
  - id: pymarkdown
    args:
      - --config
      - .pymarkdown.json
      - scan
