# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.195.0/containers/rust/.devcontainer/base.Dockerfile
# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): buster, bullseye
ARG VARIANT="bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/rust:1-${VARIANT}

COPY pyproject.toml .
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt install -y -qq python3-pip \
    # We have to remove distutils-installed PyYAML that comes with the image
    # ... causes issues when pip tries to remove or update it as it's unable
    # ... to fully uninstall it
    && apt remove -y python3-yaml \
    && apt autoremove -y \
    && python3 -m pip install --upgrade pip \
    && pip3 install poetry --quiet \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction \
    && rustup toolchain install nightly \
    && rustup override set nightly \
    && rustup component add rustfmt
